# Assignment 1 - Basic Data Exploration and Cleaning Using Pandas

# Submitted By :
Raghav_MMDU

# Role :
Data Engineer

# Objective :

The main objective of this assignment is to perform essential data exploration and data cleaning tasks using the Pandas library in Python. The assignment involves working with a CSV dataset to analyze its structure, manage missing and duplicate values, apply basic filtering operations, generate new derived columns, and prepare a clean dataset suitable for further analysis.

# Import Required Libraries

In [2]:
import pandas as pd
print("Pandas library imported successfully!")

Pandas library imported successfully!

# 1. Load a CSV dataset into a Pandas DataFrame.

In [4]:
import pandas as pd

df = pd.read_csv("data/tshirts.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999,NaN,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
6,919032,Roadster,Off-White Black Striped Speckled Pure Cotton ...,3.8,641,899,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/919...,...,"{""1_star"":73,""2_stars"":46,""3_stars"":86,""4_star...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...","[""rw-919032_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
7,18817326,Tommy Hilfiger,Men Beige & Navy Blue Striped Pure Cotton T-shirt,4.4,58,2799,40.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.03in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
8,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599,50.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"{""1_star"":36,""2_stars"":16,""3_stars"":46,""4_star...",NaN,NaN,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
9,20355284,Roadster,The Life Co. Round Neck Raglan Sleeves Typogr...,4.2,74,999,53.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":6,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
10,18818696,Tommy Hilfiger,Men White & Black Brand Logo Printed Organic C...,4.4,58,1999,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":6,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""37.4in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
11,9213113,Roadster,The Lifestyle Co Men White Printed Round Neck...,4.1,994,799,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/921...,...,"{""1_star"":74,""2_stars"":41,""3_stars"":108,""4_sta...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-9213113_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
12,13511732,Puma,Men Black Solid Run Fav 1/4 Zip T-Shirt,4.4,167,3999,NaN,"""₹3,999.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":11,""2_stars"":6,""3_stars"":7,""4_stars""...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""34.65in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
13,13591994,Camey,Men Maroon Solid Round Neck T-shirt,3.5,2,999,60.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""L"",""value"":""40.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
14,21439050,Kappa,Men Typography Printed Cotton T-shirt,3.2,9,599,30.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
15,13615634,U.S. Polo Assn.,Men Red Solid Mandarin Collar T-shirt,4.5,69,1699,40.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
16,13620624,Roadster,The Lifestyle Co Men White Brand Logo Appliqu...,4.0,154,1399,73.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":12,""2_stars"":10,""3_stars"":18,""4_star...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
17,13502414,Puma,Men Navy Blue & White Performance Cat Printed ...,4.3,327,1499,NaN,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":22,""2_stars"":11,""3_stars"":22,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""36.61in"",""value_name"":""...","[""rw-13502414_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
18,13621134,Roadster,The Lifestyle Co Men Rust Brown Solid Appliqu...,4.1,312,1399,50.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":27,""2_stars"":18,""3_stars"":31,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
19,17686030,Allen Solly Tribe,Men Navy Blue Solid T-shirt,4.3,23,1499,30.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
20,13616400,Arrow New York,Men Beige Printed Round Neck Pure Cotton T-shirt,4.8,13,899,25.0,"""₹674.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
21,13480864,Aeropostale,Men White Printed Round Neck Pure Cotton T-shirt,4.2,13,1199,NaN,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
22,13622338,Roadster,The Lifestyle Co Men Olive Green Solid Round ...,4.4,54,899,55.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",MAI███ KN███EAR███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,BEH███ HP███S A█████████LL ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
23,16295686,Miss & Chief,Boys Pack of 3 Printed T-shirt,3.9,7,1995,71.0,"""₹578.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Home,"[{""size"":""2-3Y"",""value"":""24.4in"",""value_name"":...",NaN,Hom███and███B/1█████████ Am███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
24,16298856,Friskers,Men Pack of 2 Printed Pure Cotton T-shirts,0.0,0,2998,59.0,"""₹1,229.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Fly███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
25,16277914,Parx,Men Black Printed Polo Collar T-shirt,4.9,7,1399,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ray███d L███ted███,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...",NaN,"RAY███D L███TED█████████, P███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
26,16292318,Bewakoof,Men White Printed Pockets T-shirt,4.2,17,1399,60.0,"""₹549.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Tight""...",Bew███of ███nds█████████Lim██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Plo███8, ███ Fl█████████lr,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
27,19201678,Tokyo Talkies,Women Yellow Printed Extended Sleeves Slim Fit...,4.1,103,699,58.0,"""₹293.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":4,""2_stars"":8,""3_stars"":10,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
28,16923916,Monte Carlo,Women Pack Of 2 Blue & Peach Solid V-Neck Pure...,4.8,13,835,25.0,"""₹835.00""",INR,http://assets.myntassets.com/assets/images/169...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
29,10143909,CHKOKKO,Chkokko Men Teal Green Solid Round Neck Traini...,3.7,53,1665,70.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":10,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",DLA███OSS███IVA█████████D,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,FLO███FIR███ B █████████8/1███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
30,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",NaN,Bod███ove███par█████████ No███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
31,10555034,Braveo,Men Navy Blue and Red Checked Round Neck Pure ...,0.0,0,1099,65.0,"""₹384.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bra███For███es,"[{""size"":""S"",""value"":""37.5in"",""value_name"":""Ch...",NaN,"SF.███. 8███Vad█████████am,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
32,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799,80.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
33,12953958,Allen Solly,Men Maroon Solid Polo Collar Pure Cotton T-shirt,4.4,409,999,40.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"{""1_star"":17,""2_stars"":6,""3_stars"":26,""4_stars...","[{""percentage"":""96"",""value_name"":""Fit, Just Ri...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-12953958_cae700"",""https://videos.myntasse...","Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

# 2. Explore data (head/tail, shape, columns, data types).

In [5]:
# Display first 5 rows

df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [6]:
# Display last 5 rows

df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [7]:
# Shape of dataset
print("Shape of dataset:", df.shape)

Shape of dataset: (39, 24)

In [8]:
# Column names
print(list(df.columns))

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [9]:
# Data types of each column

print(df.dtypes)

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [10]:
# Full info
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              39 non-null     int64
 1   title                   39 non-null     str
 2   product_description     39 non-null     str
 3   rating                  39 non-null     float64
 4   ratings_count           39 non-null     int64
 5   initial_price           39 non-null     int64
 6   discount                32 non-null     float64
 7   final_price             39 non-null     str
 8   currency                39 non-null     str
 9   images                  39 non-null     str
 10  delivery_options        39 non-null     str
 11  product_details         39 non-null     str
 12  breadcrumbs             39 non-null     str
 13  product_specifications  39 non-null     str
 14  amount_of_stars         39 non-null     str
 15  what_customers_said     30 non-null     str
 16  seller_name             18 non-null     str
 17  sizes                   39 non-null     str
 18  videos                  10 non-null     str
 19  seller_information      18 non-null     str
 20  variations              14 non-null     str
 21  best_offer              39 non-null     str
 22  more_offers             39 non-null     str
 23  category                39 non-null     str
dtypes: float64(2), int64(3), str(19)
memory usage: 7.4 KB
None

# 3. Handle missing values (identify, fill/drop).

In [11]:
# Checking missing values in dataset

print(df.isnull().sum())

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
seller_name               21
sizes                      0
videos                    29
seller_information        21
variations                25
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [12]:
# Removing columns with too many missing values

df = df.drop(columns=[
    'seller_name',
    'videos',
    'variations'
])

print(df.isnull().sum())

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
sizes                      0
seller_information        21
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [13]:
# Filling missing values in the dataset

df['discount'] = df['discount'].fillna('No Discount')

df['seller_information'] = df['seller_information'].fillna('Seller Details Unavailable')

df['what_customers_said'] = df['what_customers_said'].fillna('Customers Have Not Reviewed Yet')

print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
dtype: int64

 # 4. Perform basic operations (filter rows, select columns).

In [14]:
# Selecting specific columns

selected_columns = df[['title', 'final_price', 'rating']]

print(selected_columns)

                        title  final_price  rating
0                       ether  "₹1,099.00"     4.4
1              Mast & Harbour    "₹899.00"     4.2
2              Mast & Harbour    "₹999.00"     3.9
3                 Urbano Plus  "₹1,099.00"     3.2
4                     ScoldMe    "₹719.00"     0.0
5                UNDER ARMOUR  "₹1,999.00"     4.3
6                    Roadster    "₹899.00"     3.8
7              Tommy Hilfiger  "₹2,799.00"     4.4
8                       WROGN  "₹1,599.00"     4.2
9                    Roadster    "₹999.00"     4.2
10             Tommy Hilfiger  "₹1,999.00"     4.4
11                   Roadster    "₹799.00"     4.1
12                       Puma  "₹3,999.00"     4.4
13                      Camey    "₹999.00"     3.5
14                      Kappa    "₹599.00"     3.2
15            U.S. Polo Assn.  "₹1,699.00"     4.5
16                   Roadster  "₹1,399.00"     4.0
17                       Puma  "₹1,499.00"     4.3
18                   Roadster  "₹1,399.00"     4.1
19          Allen Solly Tribe  "₹1,499.00"     4.3
20             Arrow New York    "₹674.00"     4.8
21                Aeropostale  "₹1,199.00"     4.2
22                   Roadster    "₹404.00"     4.4
23               Miss & Chief    "₹578.00"     3.9
24                   Friskers  "₹1,229.00"     0.0
25                       Parx    "₹699.00"     4.9
26                   Bewakoof    "₹549.00"     4.2
27              Tokyo Talkies    "₹293.00"     4.1
28                Monte Carlo    "₹835.00"     4.8
29                    CHKOKKO    "₹499.00"     3.7
30                    BULLMER    "₹799.00"     4.8
31                     Braveo    "₹384.00"     0.0
32  AMERICAN EAGLE OUTFITTERS    "₹359.00"     4.4
33                Allen Solly    "₹599.00"     4.4
34                        max    "₹479.00"     4.4
35             Mad Over Print    "₹671.00"     4.8
36                   FERANOID    "₹599.00"     4.2
37             Flying Machine    "₹389.00"     4.0
38             Flying Machine    "₹506.00"     3.8

In [15]:
# Filtering rows based on condition

filtered_rows = df[df['rating'] > 4]

print(filtered_rows)

    product_id                      title  \
0     17352320                      ether
1     17403950             Mast & Harbour
5      8901821               UNDER ARMOUR
7     18817326             Tommy Hilfiger
8      8426447                      WROGN
9     20355284                   Roadster
10    18818696             Tommy Hilfiger
11     9213113                   Roadster
12    13511732                       Puma
15    13615634            U.S. Polo Assn.
17    13502414                       Puma
18    13621134                   Roadster
19    17686030          Allen Solly Tribe
20    13616400             Arrow New York
21    13480864                Aeropostale
22    13622338                   Roadster
25    16277914                       Parx
26    16292318                   Bewakoof
27    19201678              Tokyo Talkies
28    16923916                Monte Carlo
30    20085320                    BULLMER
32    12987894  AMERICAN EAGLE OUTFITTERS
33    12953958                Allen Solly
34    22629260                        max
35    19291812             Mad Over Print
36    19206288                   FERANOID

                                  product_description  rating  ratings_count  \
0   Kora Collection Blue Sustainable Naturally Dye...     4.4             70
1           Men Mint Green Typography Printed T-shirt     4.2            200
5       Men Charcoal Grey Big Logo SS Printed T-shirt     4.3             64
7   Men Beige & Navy Blue Striped Pure Cotton T-shirt     4.4             58
8           Men Navy Blue Striped Henley Neck T-shirt     4.2            514
9   The  Life Co. Round Neck Raglan Sleeves Typogr...     4.2             74
10  Men White & Black Brand Logo Printed Organic C...     4.4             58
11  The  Lifestyle Co Men White Printed Round Neck...     4.1            994
12            Men Black Solid Run Fav 1/4 Zip T-Shirt     4.4            167
15              Men Red Solid Mandarin Collar T-shirt     4.5             69
17  Men Navy Blue & White Performance Cat Printed ...     4.3            327
18  The  Lifestyle Co Men Rust Brown Solid Appliqu...     4.1            312
19                        Men Navy Blue Solid T-shirt     4.3             23
20   Men Beige Printed Round Neck Pure Cotton T-shirt     4.8             13
21   Men White Printed Round Neck Pure Cotton T-shirt     4.2             13
22  The  Lifestyle Co Men Olive Green Solid Round ...     4.4             54
25              Men Black Printed Polo Collar T-shirt     4.9              7
26                  Men White Printed Pockets T-shirt     4.2             17
27  Women Yellow Printed Extended Sleeves Slim Fit...     4.1            103
28  Women Pack Of 2 Blue & Peach Solid V-Neck Pure...     4.8             13
30  Men Pack of 2 Navy Blue & Turquoise Blue Long ...     4.8             12
32    Women White & Yellow Printed Round Neck T-shirt     4.4              5
33   Men Maroon Solid Polo Collar Pure Cotton T-shirt     4.4            409
34          Striped Polo Collar Short Sleeves T-shirt     4.4              7
35             Women Black Love Wins Oversize T-shirt     4.8              5
36          Men Purple Henley Neck Bio Finish T-shirt     4.2             21

    initial_price     discount  final_price currency  \
0            1099         47.0  "₹1,099.00"      INR
1             899  No Discount    "₹899.00"      INR
5            1999  No Discount  "₹1,999.00"      INR
7            2799         40.0  "₹2,799.00"      INR
8            1599         50.0  "₹1,599.00"      INR
9             999         53.0    "₹999.00"      INR
10           1999         40.0  "₹1,999.00"      INR
11            799         50.0    "₹799.00"      INR
12           3999  No Discount  "₹3,999.00"      INR
15           1699         40.0  "₹1,699.00"      INR
17           1499  No Discount  "₹1,499.00"      INR
18           1399         50.0  "₹1,399.00"      INR
19           1499         30.0  "₹1,499.00"      INR
20            899         25.0    "₹674.00"      INR
21           1199  No Discount  "₹1,199.00"      INR
22            899         55.0    "₹404.00"      INR
25           1399         53.0    "₹699.00"      INR
26           1399         60.0    "₹549.00"      INR
27            699         58.0    "₹293.00"      INR
28            835         25.0    "₹835.00"      INR
30           3998         80.0    "₹799.00"      INR
32           1799         80.0    "₹359.00"      INR
33            999         40.0    "₹599.00"      INR
34            799         40.0    "₹479.00"      INR
35           1599         58.0    "₹671.00"      INR
36           1199         50.0    "₹599.00"      INR

                                               images  ...  \
0   http://assets.myntassets.com/assets/images/173...  ...
1   http://assets.myntassets.com/assets/images/174...  ...
5   http://assets.myntassets.com/assets/images/890...  ...
7   http://assets.myntassets.com/assets/images/188...  ...
8   http://assets.myntassets.com/assets/images/842...  ...
9   http://assets.myntassets.com/assets/images/203...  ...
10  http://assets.myntassets.com/assets/images/188...  ...
11  http://assets.myntassets.com/assets/images/921...  ...
12  http://assets.myntassets.com/assets/images/135...  ...
15  http://assets.myntassets.com/assets/images/pro...  ...
17  http://assets.myntassets.com/assets/images/135...  ...
18  http://assets.myntassets.com/assets/images/136...  ...
19  http://assets.myntassets.com/assets/images/176...  ...
20  http://assets.myntassets.com/assets/images/pro...  ...
21  http://assets.myntassets.com/assets/images/134...  ...
22  http://assets.myntassets.com/assets/images/136...  ...
25  http://assets.myntassets.com/assets/images/162...  ...
26  http://assets.myntassets.com/assets/images/162...  ...
27  http://assets.myntassets.com/assets/images/192...  ...
28  http://assets.myntassets.com/assets/images/169...  ...
30  http://assets.myntassets.com/assets/images/200...  ...
32  http://assets.myntassets.com/assets/images/pro...  ...
33  http://assets.myntassets.com/assets/images/129...  ...
34  http://assets.myntassets.com/assets/images/226...  ...
35  http://assets.myntassets.com/assets/images/192...  ...
36  http://assets.myntassets.com/assets/images/192...  ...

                                      product_details  \
0   {"description":"Blue Tshirt for womenSolidRegu...
1   {"description":"Mint green T-shirt for menTypo...
5   {"description":"Special technologiesHeatGear f...
7   {"description":"Beige and navy blue T-shirt fo...
8   {"description":"Navy Blue and maroon striped T...
9   {"description":"Blue T-shirt for womenTypograp...
10  {"description":"White and black T-shirt for me...
11  {"description":"White printed T-shirt, has a r...
12  {"description":"Black solid T-shirt, has a hig...
15  {"description":"Red and Black solid T-shirt, h...
17  {"description":"Special Technologies:DRYCELL -...
18  {"description":"Rust brown solid T-shirt with ...
19  {"description":"Navy blue T-shirt for menSolid...
20  {"description":"Beige printed T-shirt, has a r...
21  {"description":"White printed T-shirt, has a r...
22  {"description":"Olive green solid T-shirt, has...
25  {"description":"Black Tshirt for menConversati...
26  {"description":"  White Tshirt for men   Conve...
27  {"description":"  Yellow Tshirt for women   Gr...
28  {"description":"Pack of two T shirts in Blue a...
30  {"description":"Pack of 2Navy blue and turquoi...
32  {"description":"White and Yellow printed T-shi...
33  {"description":"Maroon solid T-shirt, has a po...
34  {"description":"Yellow & white t-shirt for men...
35  {"description":"  Black Tshirt for women   Gra...
36  {"description":"  Purple Tshirt for men   Soli...

                                          breadcrumbs  \
0   [{"name":"Clothing","url":"https://www.myntra....
1   [{"name":"Clothing","url":"https://www.myntra....
5   [{"name":"Clothing","url":"https://www.myntra....
7   [{"name":"Clothing","url":"https://www.myntra....
8   [{"name":"Clothing","url":"https://www.myntra....
9   [{"name":"Clothing","url":"https://www.myntra....
10  [{"name":"Clothing","url":"https://www.myntra....
11  [{"name":"Clothing","url":"https://www.myntra....
12  [{"name":"Clothing","url":"https://www.myntra....
15  [{"name":"Clothing","url":"https://www.myntra....
17  [{"name":"Clothing","url":"https://www.myntra....
18  [{"name":"Clothing","url":"https://www.myntra....
19  [{"name":"Clothing","url":"https://www.myntra....
20  [{"name":"Clothing","url":"https://www.myntra....
21  [{"name":"Clothing","url":"https://www.myntra....
22  [{"name":"Clothing","url":"https://www.myntra....
25  [{"name":"Clothing","url":"https://www.myntra....
26  [{"name":"Clothing","url":"https://www.myntra....
27  [{"name":"Clothing","url":"https://www.myntra....
28  [{"name":"Clothing","url":"https://www.myntra....
30  [{"name":"Clothing","url":"https://www.myntra....
32  [{"name":"Clothing","url":"https://www.myntra....
33  [{"name":"Clothing","url":"https://www.myntra....
34  [{"name":"Clothing","url":"https://www.myntra....
35  [{"name":"Clothing","url":"https://www.myntra....
36  [{"name":"Clothing","url":"https://www.myntra....

                               product_specifications  \
0   [{"specification_name":"Add-Ons","specificatio...
1   [{"specification_name":"Add-Ons","specificatio...
5   [{"specification_name":"Add-Ons","specificatio...
7   [{"specification_name":"Add-Ons","specificatio...
8   [{"specification_name":"Body or Garment Size",...
9   [{"specification_name":"Add-Ons","specificatio...
10  [{"specification_name":"Add-Ons","specificatio...
11  [{"specification_name":"Body or Garment Size",...
12  [{"specification_name":"Add-Ons","specificatio...
15  [{"specification_name":"Add-Ons","specificatio...
17  [{"specification_name":"Add-Ons","specificatio...
18  [{"specification_name":"Add-Ons","specificatio...
19  [{"specification_name":"Add-Ons","specificatio...
20  [{"specification_name":"Add-Ons","specificatio...
21  [{"specification_name":"Add-Ons","specificatio...
22  [{"specification_name":"Add-Ons","specificatio...
25  [{"specification_name":"Add-Ons","specificatio...
26  [{"specification_name":"About the Brand","spec...
27  [{"specification_name":"Add-Ons","specificatio...
28  [{"specification_name":"Add-Ons","specificatio...
30  [{"specification_name":"About the Brand"},{"sp...
32  [{"specification_name":"Add-Ons","specificatio...
33  [{"specification_name":"Add-Ons","specificatio...
34  [{"specification_name":"Add-Ons","specificatio...
35  [{"specification_name":"Add-Ons","specificatio...
36  [{"specification_name":"Add-Ons","specificatio...

                                      amount_of_stars  \
0   {"1_star":2,"2_stars":1,"3_stars":7,"4_stars":...
1   {"1_star":14,"2_stars":10,"3_stars":16,"4_star...
5   {"1_star":6,"2_stars":2,"3_stars":4,"4_stars":...
7   {"1_star":5,"2_stars":0,"3_stars":2,"4_stars":...
8   {"1_star":36,"2_stars":16,"3_stars":46,"4_star...
9   {"1_star":6,"2_stars":1,"3_stars":6,"4_stars":...
10  {"1_star":4,"2_stars":0,"3_stars":6,"4_stars":...
11  {"1_star":74,"2_stars":41,"3_stars":108,"4_sta...
12  {"1_star":11,"2_stars":6,"3_stars":7,"4_stars"...
15  {"1_star":2,"2_stars":3,"3_stars":4,"4_stars":...
17  {"1_star":22,"2_stars":11,"3_stars":22,"4_star...
18  {"1_star":27,"2_stars":18,"3_stars":31,"4_star...
19  {"1_star":1,"2_stars":0,"3_stars":4,"4_stars":...
20  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
21  {"1_star":2,"2_stars":0,"3_stars":0,"4_stars":...
22  {"1_star":1,"2_stars":3,"3_stars":2,"4_stars":...
25  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
26  {"1_star":3,"2_stars":0,"3_stars":0,"4_stars":...
27  {"1_star":4,"2_stars":8,"3_stars":10,"4_stars"...
28  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
30  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
32  {"1_star":0,"2_stars":0,"3_stars":1,"4_stars":...
33  {"1_star":17,"2_stars":6,"3_stars":26,"4_stars...
34  {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...
35  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...
36  {"1_star":1,"2_stars":0,"3_stars":5,"4_stars":...

                                  what_customers_said  \
0   [{"percentage":"100","value_name":"Fit, Just R...
1   [{"percentage":"67","value_name":"Fit, Just Ri...
5   [{"percentage":"75","value_name":"Fit, Just Ri...
7   [{"percentage":"67","value_name":"Fit, Just Ri...
8                     Customers Have Not Reviewed Yet
9   [{"percentage":"75","value_name":"Fit, Just Ri...
10  [{"percentage":"50","value_name":"Fit, Just Ri...
11  [{"percentage":"68","value_name":"Fit, Just Ri...
12  [{"percentage":"57","value_name":"Fit, Just Ri...
15  [{"percentage":"100","value_name":"Fit, Just R...
17  [{"percentage":"78","value_name":"Fit, Just Ri...
18  [{"percentage":"86","value_name":"Fit, Just Ri...
19  [{"percentage":"100","value_name":"Fit, Just R...
20  [{"percentage":"100","value_name":"Fit, Just R...
21  [{"percentage":"100","value_name":"Fit, Just R...
22  [{"percentage":"86","value_name":"Fit, Just Ri...
25  [{"percentage":"100","value_name":"Fit, Just R...
26  [{"percentage":"100","value_name":"Fit, Tight"...
27  [{"percentage":"67","value_name":"Fit, Just Ri...
28  [{"percentage":"67","value_name":"Fit, Just Ri...
30                    Customers Have Not Reviewed Yet
32                    Customers Have Not Reviewed Yet
33  [{"percentage":"96","value_name":"Fit, Just Ri...
34                    Customers Have Not Reviewed Yet
35  [{"percentage":"100","value_name":"Fit, A Litt...
36  [{"percentage":"50","value_name":"Fit, Just Ri...

                                                sizes  \
0   [{"size":"XS","value":"32.0in","value_name":"T...
1   [{"size":"S","value":"38.0in","value_name":"Ch...
5   [{"size":"S","value":"38.0in","value_name":"Ch...
7   [{"size":"S","value":"38.03in","value_name":"C...
8   [{"size":"S","value":"37.25in","value_name":"C...
9   [{"size":"XS","value":"28.0in","value_name":"B...
10  [{"size":"XS","value":"37.4in","value_name":"C...
11  [{"size":"S","value":"38.0in","value_name":"Ch...
12  [{"size":"XS","value":"34.65in","value_name":"...
15  [{"size":"S","value":"38.0in","value_name":"Ch...
17  [{"size":"XS","value":"36.61in","value_name":"...
18  [{"size":"S","value":"38.0in","value_name":"Ch...
19  [{"size":"S","value":"38.0in","value_name":"Ch...
20  [{"size":"S","value":"38.0in","value_name":"Ch...
21  [{"size":"XS","value":"34.0in","value_name":"C...
22  [{"size":"S","value":"38.0in","value_name":"Ch...
25  [{"size":"XS","value":"42.5in","value_name":"C...
26  [{"size":"S","value":"38.0in","value_name":"Ch...
27  [{"size":"XS","value":"32.0in","value_name":"T...
28  [{"size":"S","value":"32.0in","value_name":"To...
30  [{"size":"M","value":"39.0in","value_name":"Ch...
32  [{"size":"XS","value":"29.0in","value_name":"T...
33  [{"size":"S","value":"39.0in","value_name":"Ch...
34  [{"size":"S","value":"36.0in","value_name":"Ch...
35  [{"size":"S","value":"39.3in","value_name":"Bu...
36  [{"size":"S","value":"38.0in","value_name":"Ch...

                                   seller_information  \
0                          Seller Details Unavailable
1   Sho███o. ███-10█████████enu███████████████████...
5                          Seller Details Unavailable
7                          Seller Details Unavailable
8                          Seller Details Unavailable
9                          Seller Details Unavailable
10                         Seller Details Unavailable
11                         Seller Details Unavailable
12                         Seller Details Unavailable
15                         Seller Details Unavailable
17                         Seller Details Unavailable
18                         Seller Details Unavailable
19                         Seller Details Unavailable
20                         Seller Details Unavailable
21                         Seller Details Unavailable
22  BEH███ HP███S A█████████LL ███████████████████...
25  RAY███D L███TED█████████, P███████████████████...
26  Plo███8, ███ Fl█████████lr,███████████████████...
27  3rd███oor███o. █████████Mai███████████████████...
28                         Seller Details Unavailable
30  Bod███ove███par█████████ No███████████████████...
32  Gro███ Fl███, N█████████old███████████████████...
33  Gro███ Fl███, N█████████old███████████████████...
34  #41███42/███bla█████████ pa███████████████████...
35  621███ 6n███ kh█████████zia███████████████████...
36  B15███ SH███MAR█████████RK ███████████████████...

                                           best_offer  \
0                                                  {}
1                                                  {}
5                                                  {}
7                                                  {}
8                                                  {}
9                                                  {}
10                                                 {}
11                                                 {}
12                                                 {}
15                                                 {}
17                                                 {}
18                                                 {}
19                                                 {}
20  {"applicable_on":"Orders above Rs. 1299 (only ...
21                                                 {}
22  {"applicable_on":"Orders above Rs. 1299 (only ...
25  {"applicable_on":"Orders above Rs. 999 (only o...
26  {"applicable_on":"Orders above Rs. 649 (only o...
27  {"applicable_on":"Orders above Rs. 449 (only o...
28                                                 {}
30  {"applicable_on":"Orders above Rs. 999 (only o...
32  {"applicable_on":"Orders above Rs. 649 (only o...
33  {"applicable_on":"Orders above Rs. 649 (only o...
34  {"applicable_on":"Orders above Rs. 649 (only o...
35  {"applicable_on":"Orders above Rs. 999 (only o...
36  {"applicable_on":"Orders above Rs. 649 (only o...

                                          more_offers category
0   [{"offer_name":"10% Instant Discount on Citi C...  tshirts
1   [{"offer_name":"10% Instant Discount on Citi C...  tshirts
5   [{"offer_name":"10% Instant Discount on Citi C...  tshirts
7   [{"offer_name":"10% Instant Discount on Citi C...  tshirts
8   [{"offer_name":"10% Instant Discount on Citi C...  tshirts
9   [{"offer_name":"10% Instant Discount on Citi C...  tshirts
10  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
11  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
12  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
15  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
17  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
18  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
19  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
20  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
21  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
22  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
25  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
26  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
27  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
28  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
30  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
32  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
33  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
34  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
35  [{"offer_name":"10% Instant Discount on IndusI...  tshirts
36  [{"offer_name":"10% Instant Discount on IndusI...  tshirts

[26 rows x 21 columns]

# 5. Remove duplicates.

In [16]:
# Checking duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [17]:
# Removing duplicate rows

df = df.drop_duplicates()

print("Duplicates removed successfully!")

Duplicates removed successfully!

# 6. Create a Derived Column (total_amount = price * quantity)

In [4]:
import pandas as pd

# Load dataset
df = pd.read_csv("data/tshirts.csv")

# Show columns
df[['initial_price', 'final_price']].head()

   initial_price  final_price
0           1099  "₹1,099.00"
1            899    "₹899.00"
2            999    "₹999.00"
3           1099  "₹1,099.00"
4           1598    "₹719.00"

In [5]:
df['final_price'] = df['final_price'].str.replace('₹', '')

df['final_price'] = df['final_price'].str.replace(',', '')

df['final_price'] = df['final_price'].str.replace('"', '')

df['final_price'] = df['final_price'].astype(float)

In [6]:
df['price_difference'] = df['initial_price'] - df['final_price']

In [7]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,price_difference
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099,47.0,1099.0,INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899,NaN,899.0,INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999,NaN,999.0,INR,http://assets.myntassets.com/assets/images/174...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099,45.0,1099.0,INR,http://assets.myntassets.com/assets/images/221...,...,NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,719.0,INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,879.0

# 7. Save the Cleaned Dataset as a New CSV File

In [8]:
df.to_csv("cleaned_data/cleaned_tshirts.csv", index=False)

# Assignment Summary

In this assignment, data exploration and data preprocessing operations were performed using Python and the Pandas library.

The following tasks were completed successfully:

* Loaded the CSV dataset
* Explored dataset structure, columns, and data types
* Identified and handled missing values
* Removed unnecessary columns with excessive missing data
* Checked and removed duplicate records
* Performed filtering and column selection operations
* Converted data types for numerical analysis
* Created a derived column using existing dataset columns
* Displayed and analyzed the processed dataset
* Prepared the dataset for further analysis and processing

This assignment helped in developing a practical understanding of data preprocessing, data cleaning, and data manipulation techniques using Python and Pandas.